fix: Property 'children' does not exist
Fixing Typescript error: Type '{ children: Element; enableLogging: true; }' is not assignable to type 'IntrinsicAttributes & { enableLogging?: boolean | undefined; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & { enableLogging?: boolean | undefined; }'